# Generated by Django 5.2.1 on 2025-05-10 01:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_code', message='O código deve estar no formato 9999-9.', regex='^\\d{4}-\\d$')])),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ERROR', 'Erro'), ('SUCCESS', 'Sucesso'), ('PROCESSING', 'Processando')], default='PROCESSING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
