# Generated by Django 5.2.2 on 2025-06-26 01:06

import bot.models

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_code', message='O código deve estar no formato 9999-9.', regex='^\\d{4}-\\d$')])),
                ('quantity', models.IntegerField()),
                ('type', models.IntegerField()),
                ('status', models.CharField(choices=[('ERROR', 'Erro'), ('SUCCESS', 'Sucesso'), ('PROCESSING', 'Processando')], default='PROCESSING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=1024, null=True)),
                ('can_retry', models.BooleanField(default=False)),
                ('mapped_type', models.IntegerField(blank=True, null=True)),
                ('month_of_competence', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default=bot.models.AutomationHistory.previous_month, max_length=2)),
                ('year_of_competence', models.CharField(default=bot.models.AutomationHistory.current_year, max_length=4, validators=[django.core.validators.RegexValidator(code='incorrect_year_of_competence', message='O código deve estar no formato 9999.', regex='^\\d{4}')]))
            ],
        )
    ]
