# Generated by Django 4.2.23 on 2025-06-26 01:36

from django.db import migrations

def populate_table(apps, schema_editor):
    TypesOfTaxation = apps.get_model('bot', 'TypesOfTaxation')
    data = [
        {'code': 1, 'description': 'Normal', 'mapped_value': 100, 'should_run_automation': True},
        {'code': 2, 'description': 'Desconto - 80%', 'mapped_value': None, 'should_run_automation': False},
        {'code': 3, 'description': 'Desconto - 50% SFH', 'mapped_value': 50, 'should_run_automation': True},
        {'code': 4, 'description': 'Desconto - 50% Minha Casa Minha Vida', 'mapped_value': None, 'should_run_automation': False},
        {'code': 5, 'description': 'Desconto - 75% Minha Casa Minha Vida', 'mapped_value': None, 'should_run_automation': False},
        {'code': 6, 'description': 'Desconto - 75% FAR/FDS', 'mapped_value': 25, 'should_run_automation': True},
        {'code': 7, 'description': 'Desconto - 90% Minha Casa Minha Vida', 'mapped_value': None, 'should_run_automation': False},
        {'code': 8, 'description': 'Desconto - 80% Minha Casa Minha Vida', 'mapped_value': None, 'should_run_automation': False},
        {'code': 9, 'description': 'Isento - Administração Direta do Estado', 'mapped_value': None, 'should_run_automation': False},
        {'code': 10, 'description': 'Isento - Mandado Judicial + justiça gratuita', 'mapped_value': None, 'should_run_automation': False},
        {'code': 11, 'description': 'Isento - Declaradamente Pobres', 'mapped_value': None, 'should_run_automation': False},
        {'code': 12, 'description': 'Isento - Credor', 'mapped_value': None, 'should_run_automation': False},
        {'code': 13, 'description': 'Isento - Penhora e Arresto', 'mapped_value': None, 'should_run_automation': False},
        {'code': 14, 'description': 'Isento - Programa Habitação', 'mapped_value': None, 'should_run_automation': False},
        {'code': 15, 'description': 'Isento - Interesse da União', 'mapped_value': None, 'should_run_automation': False},
        {'code': 16, 'description': 'Isento - Entidades de assistência social/desenvolvimento socioeconômico de natureza rural/atividades comunitárias rurais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 17, 'description': 'Isento - Regularização Fundiária de Interesse Social', 'mapped_value': None, 'should_run_automation': False},
        {'code': 18, 'description': 'Isento - Certidão Justiça Eleitoral', 'mapped_value': None, 'should_run_automation': False},
        {'code': 19, 'description': 'Isento - Certidões para Órgãos Públicos', 'mapped_value': None, 'should_run_automation': False},
        {'code': 20, 'description': 'Isento - Promorar-Militar', 'mapped_value': None, 'should_run_automation': False},
        {'code': 21, 'description': 'Desconto - 90% Promorar-Militar', 'mapped_value': None, 'should_run_automation': False},
        {'code': 22, 'description': 'Desconto - 80% Promorar-Militar', 'mapped_value': None, 'should_run_automation': False},
        {'code': 23, 'description': 'Isento TFJ - Micro Empresa e Empresa de Pequeno Porte', 'mapped_value': None, 'should_run_automation': False},
        {'code': 24, 'description': 'Devedor', 'mapped_value': None, 'should_run_automation': False},
        {'code': 25, 'description': 'Isento TFJ', 'mapped_value': None, 'should_run_automation': False},
        {'code': 26, 'description': 'Isento - Nascimento/Óbito + certidão', 'mapped_value': None, 'should_run_automation': False},
        {'code': 27, 'description': 'Isento - Minha Casa Minha Vida', 'mapped_value': None, 'should_run_automation': False},
        {'code': 28, 'description': 'Ato retificador/renovador em razão de erro imputável ao próprio cartório', 'mapped_value': None, 'should_run_automation': False},
        {'code': 29, 'description': 'Isento - Nascimento/Óbito + certidão', 'mapped_value': None, 'should_run_automation': False},
        {'code': 30, 'description': 'Isento - Estado de Minas Gerais e suas autarquias e fundações', 'mapped_value': None, 'should_run_automation': False},
        {'code': 31, 'description': 'Isento - Retificação/renovação/restauração/suprimento em razão de erro imputável ao Oficial/Tabelião ou preposto', 'mapped_value': None, 'should_run_automation': False},
        {'code': 32, 'description': 'Isento - reserva legal', 'mapped_value': None, 'should_run_automation': False},
        {'code': 33, 'description': 'Isento - associações de moradores', 'mapped_value': None, 'should_run_automation': False},
        {'code': 34, 'description': 'Registro ou averbação de cédulas e letras de crédito imobiliário e de cédulas de crédito bancário, quando solicitado(a) simultaneamente com o registro da garantia do crédito respectivo', 'mapped_value': None, 'should_run_automation': False},
        {'code': 35, 'description': 'Devedor + Isento TFJ - Microempresa e Empresa de Pequeno Porte', 'mapped_value': None, 'should_run_automation': False},
        {'code': 36, 'description': 'Isento - Reforma Agrária/Assentamento - Beneficiários de terras rurais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 37, 'description': 'Desconto - 50% Programa de Arrendamento Residencial', 'mapped_value': None, 'should_run_automation': False},
        {'code': 38, 'description': 'Averbação/registro relativo ao mesmo ato/negócio jurídico, realizados na matrícula de origem do imóvel e em cada uma das matrículas das unidades autônomas eventualmente abertas', 'mapped_value': None, 'should_run_automation': False},
        {'code': 39, 'description': 'Desconto - 90% Doação de Imóveis pelo Estado de Minas Gerais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 40, 'description': 'Isento TFJ e desconto de 90% sobre os emolumentos', 'mapped_value': None, 'should_run_automation': False},
        {'code': 41, 'description': 'Isento - Reconhecimento de Firma em requerimentos e papéis destinados a fins eleitorais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 42, 'description': 'Prenotação - Autoridade Judiciária', 'mapped_value': None, 'should_run_automation': False},
        {'code': 43, 'description': 'Prenotação - Parte Interessada', 'mapped_value': None, 'should_run_automation': False},
        {'code': 44, 'description': 'Averbação de retificação de registro civil das pessoas naturais para correção de erro que não exija qualquer indagação', 'mapped_value': None, 'should_run_automation': False},
        {'code': 45, 'description': 'Apostila - Convenção de Haia', 'mapped_value': None, 'should_run_automation': False},
        {'code': 46, 'description': 'Isento - Averbação de CPF', 'mapped_value': None, 'should_run_automation': False},
        {'code': 47, 'description': 'Desconto - 75% Registro de hipoteca/alienação fiduciária relacionado a cédula/nota de crédito rural cuja área da garantia real não ultrapasse quatro módulos fiscais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 48, 'description': 'Isento - Bem/direito doado ao Estado, suas autarquias e fundações', 'mapped_value': None, 'should_run_automation': False},
        {'code': 49, 'description': 'Desconto - 50% Imóvel financiado por entidade financeira/Estado/Município', 'mapped_value': None, 'should_run_automation': False},
        {'code': 50, 'description': 'Registro/averbação de cédula rural pignoratícia/de produto rural garantida por penhor rural, exclusivamente no Livro 3', 'mapped_value': None, 'should_run_automation': False},
        {'code': 51, 'description': 'Isento - Protocolo em registro/custódia de documentos eletrônicos (item 5, "c", "d", "e")', 'mapped_value': None, 'should_run_automation': False},
        {'code': 52, 'description': 'Certidão de processo de habilitação ou de outro procedimento (termo de abertura e termo de encerramento) e cada uma das páginas reproduzidas', 'mapped_value': None, 'should_run_automation': False},
        {'code': 53, 'description': 'Registro de certidões expedidas pelo Poder Judiciário relativas a precatórios judiciais.', 'mapped_value': None, 'should_run_automation': False},
        {'code': 54, 'description': 'Registro de hipoteca/alienação fiduciária relacionado a cédula/nota de crédito rural e de produto rural', 'mapped_value': None, 'should_run_automation': False},
        {'code': 55, 'description': 'Apresentação/distribuição a protesto - pagamento postergado', 'mapped_value': None, 'should_run_automation': False},
        {'code': 56, 'description': 'Apresentação/distribuição a protesto - pagamento quando da elisão/desistência/cancelamento/sustação', 'mapped_value': None, 'should_run_automation': False},
        {'code': 57, 'description': 'Cancelamento da distribuição por vício formal do título', 'mapped_value': None, 'should_run_automation': False},
        {'code': 58, 'description': 'Prenotação - mandado judicial - Autoridade Judiciária', 'mapped_value': None, 'should_run_automation': False},
        {'code': 59, 'description': 'Prenotação - mandado judicial - Parte Interessada', 'mapped_value': None, 'should_run_automation': False},
        {'code': 60, 'description': 'Prenotação - indisponibilidade de bens - Autoridade', 'mapped_value': None, 'should_run_automation': False},
        {'code': 61, 'description': 'Prenotação - indisponibilidade de bens - Parte Interessada', 'mapped_value': None, 'should_run_automation': False},
        {'code': 62, 'description': 'Isento - Procuração para recebimento de benefícios previdenciários/assistenciais (INSS) + traslado', 'mapped_value': None, 'should_run_automation': False},
        {'code': 63, 'description': 'Autenticação e averbação de alteração de ato constitutivo de organização da sociedade civil - desconto de 25%', 'mapped_value': None, 'should_run_automation': False},
        {'code': 64, 'description': 'Desconto 50% - Registro de hipoteca, alienação fiduciária de bem imóvel ou móvel e penhor, relacionados a contratos firmados por meio de cédula de crédito rural, de cédula de produto rural, bem como de cédula de crédito bancário para fins rurais', 'mapped_value': None, 'should_run_automation': False},
        {'code': 65, 'description': 'Desconto 75% - Registro de hipoteca, alienação fiduciária de imóvel/móvel e penhor - contratos firmados por meio de cédula de crédito rural/produto rural/crédito bancário p/ fins rurais - crédito do Pronaf ou em favor do agricultor familiar com DAP', 'mapped_value': None, 'should_run_automation': False},
        {'code': 66, 'description': 'Isenção TFJ - Protesto envolvendo devedor inscrito no CadÚnico, microempresa ou empresa de pequeno porte', 'mapped_value': None, 'should_run_automation': False},
        {'code': 67, 'description': 'Desconto 50 % - Cancelamento de protesto de títulos apresentados entre 20/3/2020 e 31/12/2022 (Estado de Emergência em Saúde Pública de Importância Internacional) e entre 1º/1/2023 e 31/12/2023 (Desenrola Brasil)', 'mapped_value': None, 'should_run_automation': False},
        {'code': 68, 'description': 'Desconto 50% - Registro de compromisso de compra e venda, cessão, promessa de cessão ou de promessa de permuta', 'mapped_value': None, 'should_run_automation': False},
        {'code': 69, 'description': 'Isenção - Atos praticados em cumprimento de decisão administrativa do Poder Judiciário', 'mapped_value': None, 'should_run_automation': False},
        {'code': 70, 'description': 'Desconto 50% - Escritura envolvendo transação que admita instrumentalização de forma particular', 'mapped_value': None, 'should_run_automation': False},
        {'code': 71, 'description': 'Desconto 80% - Escritura pública para aquisição de imóveis financiados por entidade financeira integrante do SFI ou do SFH, cooperativa de crédito ou administradora de consórcio de imóveis - Nota XXIII da Tabela 1 anexa à Lei estadual nº 15.424/2004', 'mapped_value': None, 'should_run_automation': False},
        {'code': 72, 'description': 'Isenção TFJ + Desconto 50% - Cancelamento de protesto de títulos apresentados entre 20/3/2020 e 31/12/2022 e entre 1º/1/2023 e 31/12/2023 + devedor inscrito no CadÚnico, microempresa ou empresa de pequeno porte - arts. 19-A e 19-B da Lei estadual nº 15.424/2004', 'mapped_value': None, 'should_run_automation': False},
        {'code': 73, 'description': 'Isento - Ato praticado de ofício', 'mapped_value': None, 'should_run_automation': False},
        {'code': 74, 'description': 'Cumprimento de ordem judicial independentemente de emolumentos e TFJ - sem justiça gratuita', 'mapped_value': None, 'should_run_automation': False},
        {'code': 75, 'description': 'Isento - serviços eletrônicos disponibilizados aos entes previstos', 'mapped_value': None, 'should_run_automation': False},
        {'code': 76, 'description': 'Desconto - 50% Escritura pública autorizando o inventariante a alienar bens do espólio', 'mapped_value': None, 'should_run_automation': False},
    ]

    for item in data:
        TypesOfTaxation.objects.update_or_create(code=item['code'], defaults=item)

class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_table),
    ]
